### ISSUE TITLE
Allow persisting spinner at end of terminal

### ISSUE THREAD

**Issue by skulldogged** [ad4mx/spinoff#11]
**Is your feature request related to a problem? Please describe.**
I'm using this crate in a program I'm building, and I'd like to be able to have the spinner stay at the bottom while a command is running and printing out to stdout. Currently, the command being ran and the spinner end up "z-fighting" in a way.

**Describe the solution you'd like**
The spinner would stay at the bottom of the terminal, while the command streams to stdout above the spinner.

**Describe alternatives you've considered**
I have not found any alternatives at this point.

**Comment by ad4mx** [comment]
Hi, I'm afraid this won't be possible since "refreshing" the spinner to a new frame involves deleting the last line and reprinting it again (this is the root cause of your "z-fighting" issue).
