### ISSUE TITLE
Split each spinner into a feature

### ISSUE THREAD

**Issue by peaske7** [ad4mx/spinoff#15]
Most people only need one or two spinners. Instead of having the user install all 80+ spinners, we can use features so that they only need to install the specific spinner they want. 

With this change, iterating over all spinner variants will not be supported out of the box and, instead, will need to be implemented by the user. People installing all 80+ spinners will also have a slightly larger crate to install (due to the individual implementations for each spinner). Still, this crate will be able to drop `maplit` and `strum` as dependencies, as they will no longer be necessary.

However, this change has a delightful side effect of allowing `SpinnerFrames` data to be decoupled with the core of the crate itself. Users, if they so wish to, will now be able to implement and run their custom spinner using a macro provided by this crate while still reaping the ergonomics that this crate offers, allowing for much more extensibility.

We can easily achieve this without changing the interface by using macros and tweaking the library just a bit; We can also have the default feature set to `all` to ease the transition.

An example of what it could look like: 

```rust
// The generated code (from the macro) could have an empty struct, a way to
// convert the struct into `SpinnerFrames`, and the actual static value itself.
pub struct Dots;

impl From<Dots> for SpinnerFrames {
    fn from(_: Dots) -> SpinnerFrames {
        DOTS_SPINNER.clone()
    }
}

static DOTS_SPINNER: Lazy<SpinnerFrames> = Lazy::new(|| SpinnerFrames {
    frames: vec!["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"],
    interval: 80
});

// If a user has the `dots` feature enabled, a new spinner could be created 
// with the same interface as the current one
Spinner::new(Spinners::Dots, "Hello world!", None);
```

What do you think?
I already have a fork for https://github.com/FGRibreau/spinners implementing this change, so adjusting it and porting it to this crate should be easy. If you don't have any fundamental objections, I would like to submit a PR, though, I fully understand if you don't want this.

**Comment by ad4mx** [comment]
Hi, amazing idea! I've been thinking of implementing custom spinners for quite a long time, however I didn't have enough free time to work on it.  With how I understand this, it looks good. If you want, send in a PR and I'll look at it.

One question though, will we need to generate every spinner variant we already have with a macro?

**Comment by peaske7** [comment]
Yeah, I think we should.
