### ISSUE TITLE
Implement Copy trait

### ISSUE THREAD

**Issue by EdgardoArriagada** [ad4mx/spinoff#19]
**Is your feature request related to a problem? Please describe.**

Cannot implement Facade pattern because there is no implementation of the Copy trait 🤕 

**Describe the solution you'd like**

implement copy/clone (I'm new to rust, please forgive me if it doesn't makes sense 🙏 )

**Describe alternatives you've considered**

using [spinners](https://github.com/FGRibreau/spinners) lib for facade (it worked ✅ )

**Additional context**
```rust
use spinoff::{spinners, Color, Spinner as LibSpinner};

pub struct Spinner {
    msg: String,
    sp: LibSpinner,
}

impl Spinner {
    pub fn new(msg: &String) -> Self {
        Self {
            msg: msg.clone(),
            sp: create_standard_spinner(&msg),
        }
    }

    pub fn success(&mut self) {
        self.sp.success(&self.msg);
    }
}

fn create_standard_spinner(msg: &String) -> LibSpinner {
    LibSpinner::new(spinners::Dots2, msg.clone(), Color::Blue)
}

pub fn create_spinner(msg: &String) -> Spinner {
    Spinner::new(msg)
}

```

but it results in the following error

```bash
error[E0507]: cannot move out of `self.sp` which is behind a mutable reference
  --> shared/commands-helper/src/lib.rs:23:13
   |
23 |             self.sp.success(&self.msg);
   |             ^^^^^^^ move occurs because `self.sp` has type `spinoff::Spinner`, which does not implement the `Copy` trait

For more information about this error, try `rustc --explain E0507`.
                 ^^^^
```

**Comment by ad4mx** [comment]
Hi, this will not be possible, since the struct every spinner is built on, `SpinnerFrames`, has a field with a `Vec<&'static str>`, so I can't implement the Copy trait on it. You can clone it however.
```rust
#[derive(Debug, Clone)]
pub struct SpinnerFrames {
    pub frames: Vec<&'static str>,
    pub interval: u16,
}
```
