### ISSUE TITLE
Automatic spinner animation data.

### ISSUE THREAD

**Issue by mainrs** [ad4mx/spinoff#2]
Hey!

I stumbled across this crate on reddit. I have pretty much the same crate: https://github.com/mainrs/terminal-spinners-rs. I do have a repository that automatically updates spinner definitions based on sindresorphus spinner library.

https://github.com/mainrs/terminal-spinner-data-rs

If you need anything additionally api wise, feel free to open an issue.

Cheers!

**Comment by ad4mx** [comment]
Hi, I'm probably not going to need to use your spinner data constants as I have everything neatly organized in a HashMap, but it's great you reached out. 

I saw your terminal-spinner-rs crate before, and actually even took some inspiration from it in my code, so thanks for that! 😁

**Comment by mainrs** [comment]
No problem! Did you figure out a way to solve/work around https://github.com/mainrs/terminal-spinners-rs/issues/11? After each frame I always sleep as long as the animation duration of the spinner. I couldn't come up with something cleaner that does not involve double checking for new text at the start end end of the rendering.

**Comment by ad4mx** [comment]
I left some comments in that issue. Hope they are helpful.
