### ISSUE TITLE
Undefined behaviour when used with rayon (parllel iterators)

### ISSUE THREAD

**Issue by rawhuul** [ad4mx/spinoff#24]
**Describe the bug**
Hey there, I have a function which shows spinner as needed and the function is as follows:
```rust
fn sync(name: &str, url: &str) -> Result<SyncStatus, <Self as Sync>::Error> {
        let temp_dir_builder = TempDir::build()?;
        let temp_dir = temp_dir_builder.path();

        let mut sp = Spinner::new(
            spinners::Dots,
            format!("Fetching bucket {name}..."),
            Color::Blue,
        );

        let repo = RepoBuilder::new()
            .clone(url, &temp_dir)
            .map_err(|_| ScoopieError::Sync(SyncError::UnableToFetchRepo))?;

        let head = repo
            .head()
            .map_err(|_| ScoopieError::Sync(SyncError::UnableToGetHead))?;

        let commit_id = head
            .peel_to_commit()
            .map_err(|_| ScoopieError::Sync(SyncError::UnableToGetCommit))?
            .id()
            .to_string();

        let bucket_dir = Config::buckets_dir()?;
        let bucket_path = bucket_dir.join(name);

        sp.update_text(format!("Reading metadata for bucket {name}"));
        let mut metadata = MetaData::read()?;

        let st = match (
            bucket_path.exists(),
            metadata.get(name).commit_id == commit_id,
        ) {
            (true, true) => SyncStatus::UpToDate(name.into()),
            (true, false) => {
                sp.update_text(format!("Reading manifests from bucket {name}..."));
                Self::read(&temp_dir)?.write_to(&bucket_path);
                metadata.write(name, url, &commit_id)?;
                SyncStatus::Synced(name.into())
            }

            (false, _) => {
                sp.update_text(format!("Reading manifests from bucket {name}"));
                Self::read(&temp_dir)?.write_to(&bucket_path);
                metadata.write(name, url, &commit_id)?;
                SyncStatus::Created(name.into())
            }
        };

        match st {
            SyncStatus::UpToDate(_) => {
                sp.success(&format!("Bucket: {name} is already synced to remote"))
            }
            SyncStatus::Synced(_) => sp.success(&format!("Bucket: {name} synced to remote")),
            SyncStatus::Created(_) => sp.success(&format!("Bucket: {name} has been created")),
        };

        Ok(st)
}
```
And it has been called as:

```rust
Config::read()?
            .known_buckets()
            .par_iter()
            .map(|v| Bucket::sync(v.0, v.1))
            .collect()
```

**Expected behavior**
A clear spinner with text from each function in one line but it outputs zibberish.

**Screenshots**

https://github.com/ad4mx/spinoff/assets/84739019/422f0aab-3ee4-4136-8dc3-376ae8902b4a

**Comment by ad4mx** [comment]
Hi, thanks for the issue. I am not exactly sure where the issue in the library's code is - but it's clear there's a problem. Just so I am on the same page, the constant flickering between `Fetching bucket extras` and `Fetching bucket main` is also a bug or is it expected behavior?

**Comment by rawhuul** [comment]
> Hi, thanks for the issue. I am not exactly sure where the issue in the library's code is - but it's clear there's a problem. Just so I am on the same page, the constant flickering between `Fetching bucket extras` and `Fetching bucket main` is also a bug or is it expected behavior?

Yes the constant flickering between text is bug, it is expected that every text gets its new line but I also tried it with `\n`, where I get repeated amount of same text in each line.

**Comment by ad4mx** [comment]
The main problem is that the library wasn't *really* written with parallel iterators in mind.  Unfortunately I don't have enough time to find a possible solution to this at the moment. In the meantime,  consider trying other rust spinner libraries like `spinners`, maybe they could work. It's possible that some features included in `spinoff` may be missing in other libraries of this kind though.

**Comment by rawhuul** [comment]
Thanks, I would also try to look into it.
