### ISSUE TITLE
A space is inserted before a spinner

### ISSUE THREAD

**Issue by Milo123459** [ad4mx/spinoff#5]
Was just using it now, when I realised spinoff seems to be adding a space before the spinner. Any ideas?
<img width="80" alt="image" src="https://user-images.githubusercontent.com/50248166/182001651-e5f84999-6d12-4d91-a418-269a6b9969cd.png">

PS: I'm using Spinnners::Dots.

**Comment by adamtehbloxxer** [comment]
Hi, seems to be a typo. I’ll include the fix in the next version.

**Comment by ad4mx** [comment]
Should be fixed in v0.5.3.
