### ISSUE TITLE
Colours not working in Windows

### ISSUE THREAD

**Issue by RubyBit** [ad4mx/spinoff#6]
**Describe the bug**
In a Windows command line terminal, colours are not correctly displayed, instead random letters and symbols are (which I assume is the supposed syntax for the colour). This seems to be a problem with the colored crate but I would suggest to at least when using the None option for the colours to add no such syntax at all and just the spinner with the text (looking on how its done in the source code).

**To Reproduce**
1. Create any spinner with any color (includine the None option)
3. Open the created binary on a windows command line terminal (not the new Windows Terminal)

**Expected behavior**
A colour should be displayed (again, probably an error with the colored crate)

**Desktop:**
 - OS: Windows

**Additional info**
This might not be able to be fixed by you (see above with the colored crate) but I like your crate so the suggested fix would be nice, so I can use the spinners without the colours :)

**Comment by RubyBit** [comment]
This might be interesting (was looking through the colored crate issues), seems to include a possible fix for at least windows 10 with the control::set_virtual_terminal function.
https://github.com/mackwic/colored/issues/59

**Comment by ad4mx** [comment]
Hi, I'm going to fix it as soon as I can.

**Comment by ad4mx** [comment]
Hi @RubyBit, could you please run #7's branch's examples locally to tell me if anything changed? I want to see if I still can use the colored crate or if I should switch.

**Comment by RubyBit** [comment]
I tested it and normal (without colour) mode works nicely but the problem persists with coloured text. Testing it with the set_virtual_terminal function, the colours as well as symbols are correctly displayed! 

![image](https://user-images.githubusercontent.com/35471908/187804230-c5f1950c-2ad1-4df1-a3b8-a4b80d434d12.png)

I also want to mention as I failed to mention this in the bug report, this happens when a console is allocated(through AllocConsole) to my process (which doesnt have one), and the white colour could not be displayed for some reason (I tested with the white colour in a normal command prompt project and it worked fine). Nevertheless, set_virtual_terminal adds full functionality for all colours and symbols at both cases.

**Comment by ad4mx** [comment]
I'm happy that it works now. I reckon I could include `set_virtual_terminal` in the code as an OS specific thing so the user doesn't have to bother with it?

**Comment by RubyBit** [comment]
Yes that would be nice and I believe easily implemented with a conditional statement using the `cfg!` macro. I think it is quite important here as it allows for not only colours but every symbol to be properly displayed in a windows command line prompt (thus the crate works as intended in windows).

**Comment by ad4mx** [comment]
Right, should be added to the branch now. Could you just verify for the last time that it works without explicitly setting the virtual terminal like before?

**Comment by ad4mx** [comment]
After that, it should be ready for a merge.

**Comment by RubyBit** [comment]
Everything seems to work but I am not sure if the branch will compile in other OSes as you use a conditional compiled function in a function which is compiled on all OSes ( I have added a comment on the code with a potential fix)

**Comment by ad4mx** [comment]
Right, That seems to be an issue. Where did you add your comment? I can't see it anywhere.

**Comment by RubyBit** [comment]
If you go to the pull request, it is there. I was just saying to immediately set ``control::set_virtual_terminal(true)`` if the cfg! conditional is true without referring to the conditional function (thus removing the build error)

**Comment by ad4mx** [comment]
Setting it directly in the cfg! conditional doesn't actually seem to do anything since the set_virtual_terminal function is target_os limited by default so our build environment (ubuntu) won't be able to find it.

**Comment by ad4mx** [comment]
To me, it looks like unfortunately the user will have to set it themselves. I could, however include a note in the readme so users won't get confused.

**Comment by RubyBit** [comment]
Yes that should work and be quite straight forward.
